name: Build neu

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

      steps: 
        - name: Checkout
          uses:  actions/checkout@v4
          with:
            java-version: '17'
            distribution: 'temurin'

        - name: Buildjar
          run: mvn clean

        - name: Copy JAR to Aya-GlassFish via SCP
          uses: appleboy/scp-action@v1
          with:
            host: 161.35.74.206
            username: tln1
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            port: 22
            source: "target/*.jar"
            target: "/home/tln1/"
