name: Build

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

      steps:
        - name: Checkout
          uses:  actions/checkout@v4
          with:
            java-version: '17'
            distribution: 'temarin'

        - name: Buildjar
          run: mvn clean
